version: '3.8'

services:
  mongo-db:
    image: mongo:4.4.3-bionic
    restart: unless-stopped
    ports:
      - '27017:27017'

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./workshop-mongo/target:/tmp
    ports:
        - "8080:8080"
    depends_on:
      - mongo-db
    environment:
      - SPRING_DATASOURCE_URL=mongodb://mongo-db:27017/workshop_mongo